(function(){
	var style = $("<style>.popup-box{background-color:#ffffff;/* bottom:0;height:80%;position:fixed;right:30px; width:100%;bottom:75px;transition:all 0.2s ease-in;transform:translateY(calc(100% + 120px));border-radius:8px;overflow:hidden;*/max-width:400px;font-family:'Open Sans', sans-serif;box-shadow:rgba(0, 0, 0, 0.16) 0px 5px 40px;border-bottom-right-radius: 20px;border-bottom-left-radius: 20px;padding: 0px; position: fixed; z-index: 2147483646; border-radius: 16px; bottom: 85px; top: auto; width: 399px; max-height: 0px; right: 4px; margin-right: 12px; min-height: 0px; height: 732px;} .popup-box.active-chatbox{/* transform:translateY(0); */max-height: calc(100% - 80px);max-height: calc(100% - 80px); height: 732px; min-height: 360px; animation-duration: 300ms; /* animation-name: bounce_in; transition-timing-function: ease-in; */} #showcharbox{height:100%;} .chat-btn{color:#fff;border-radius:50px;outline:none !important;position:fixed;bottom:2%;right:2%;font-size:20px;width:55px;height:55px;transition:all 0.2s ease-in;background:none;} .chat-btn.focus, .chat-btn:focus, .chat-btn:hover{color:#fff;text-decoration:none;} .close-icon{background: url(https://mindpathtech.blob.core.windows.net/chatbot/travel-booking/assets/logo.svg) no-repeat 14px center;height: 60px; width: 50px;background-size: 100% 100%;transform: rotate(180deg);filter: invert(63%) sepia(43%) saturate(1745%) hue-rotate(328deg) brightness(99%) contrast(103%);} .chat-icon {background: url(https://mindpathtech.blob.core.windows.net/chatbot/travel-booking/assets/logo.svg) no-repeat 14px center;height: 60px; width: 50px;display: block;filter: invert(63%) sepia(43%) saturate(1745%) hue-rotate(328deg) brightness(99%) contrast(103%);} @media (max-width:450px) { .popup-box { max-width: 300px; }}@keyframes bounceIn {0% {opacity: 0;	-webkit-transform: scale(.3);-ms-transform: scale(.3);transform: scale(.3)}	50% {opacity: 1;-webkit-transform: scale(1.05);	-ms-transform: scale(1.05);	transform: scale(1.05)}	70% {-webkit-transform: scale(.9);-ms-transform: scale(.9);	transform: scale(.9)}100% {	opacity: 1;	-webkit-transform: scale(1);-ms-transform: scale(1);transform: scale(1)}}.bounceIn {-webkit-animation-name: bounceIn;animation-name: bounceIn}	@keyframes bounceOut {0% {-webkit-transform: scale(1);-ms-transform: scale(1);transform: scale(1)}25% {	-webkit-transform: scale(.95);-ms-transform: scale(.95);transform: scale(.95)}50% {	opacity: 1;	-webkit-transform: scale(1.1);-ms-transform: scale(1.1);transform: scale(1.1)}100% {opacity: 0;	-webkit-transform: scale(.3);-ms-transform: scale(.3);transform: scale(.3)}	}.bounceOut {-webkit-animation-name: bounceOut;	animation-name: bounceOut}</style>");
	var html = $('<button class="chat-btn" id="hidechatbtn"><i class="chat-icon"></i></button><div class="popup-box chat-popup" style="padding: 0px; position: fixed; z-index: 2147483646; border-radius: 16px; bottom: 85px; top: auto; width: 399px; max-height: 0px; right: 4px; margin-right: 12px; min-height: 0px;"><div id="showcharbox"><object width="100%" height="100%" type="text/html" data="https://mindpathtech.blob.core.windows.net/chatbot/travel-booking/index.html"></object></div></div>');
	var element = $('#chatbot');

	$('#chatbot').append([style, html]);

	$("#hidechatbtn").on("click", function (t) {
		$(this).find("i").toggleClass("close-icon"), t.preventDefault(), $(".popup-box, .bounceOut").toggleClass("active-chatbox").toggleClass("bounceIn");
	});
})();